baseURL = 'https://tranquilpeak.dev.acsr.de/'
languageCode = "de-de"
defaultContentLanguage = "de-de"
title = 'acsr Tranquilpeak Demo Site'
theme = "tranquilpeak"
[params]
  dateFormat = "02. January 2006"